name: CI

on:
  issues:
    types: [ labeled ]

env:
  LABEL_NAME: help wanted

jobs:
  build:
    if: ${{ github.event.label.name }} == $LABEL_NAME
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        #cache: 'pip'

    - name: Install dependencies
      run: pip install loguru omegaconf openai

    - name: Write issue details to disk
      run: |
        echo "Issue number: ${{ github.event.issue.number }}"
        echo "${{ github.event.issue.title }}" > issue_details.txt
        echo "${{ github.event.issue.body }}" >> issue_details.txt

    - name: Do the thing
      run: | 
        echo "Issue number: ${{ github.event.issue.number }}"
        #echo "Issue title: ${{ github.event.issue.title }}"
        #echo "Issue body: ${{ github.event.issue.body }}"
        echo "do the thing"
        python do_the_thing.py issue_details.txt
      #env:
      #  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: LLM auto-completed.
        branch: llm-autocompletion
        branch-suffix: ${{ github.event.issue.number }}
