name: CI

on:
  issues:
    types: [ labeled ]

env:
  LABEL_NAME: help wanted

jobs:
  build:
    if: ${{ github.event.label.name }} == $LABEL_NAME
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        #cache: 'pip'

    - name: Install dependencies
      run: pip install omegaconf openai
      
#     - name: Run draw_owl.py
#       run: python draw_owl.py
#       env:
#         OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    - name: Install dependencies
      run: | 
        echo "do the thing"
        echo "${{ github.event.id }}"
        echo "${{ github.event.event_id }}"
        echo "${{ github.event.name }}"

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: LLM auto-completed.
        branch: llm-autocompletion
        branch-suffix: timestamp
